### ISSUE TITLE
[Btnroles] not working 

### ISSUE THREAD

**Issue by Slurpcy** [Bakersbakebread/BreadCogsV3#23]
Error: Exception in command 'setroles'
Traceback (most recent call last):
  File "c:\users\alex\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\alex\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\lord\cogs\CogManager\cogs\btnroles\btnroles.py", line 46, in setroles
    emoji=config.get(emoji),
AttributeError: 'str' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\alex\redenv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "c:\users\alex\redenv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\users\alex\redenv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'get'

my yaml File:
![632CD24E-D752-4D45-897B-931CDAB0D059](https://user-images.githubusercontent.com/75667833/135335067-5622dbc9-670e-4922-b6c4-5ad665de3bfd.jpeg)

**Comment by Slurpcy** [comment]
Thanks to bread the issue got fixed turns out was a mistake that I made in my YAML file, a proper yaml file will be like this(for anyone else who doesn't know the format): 

```yaml
Name_on_the_button(aka label):
                                                             style: 1,2 etc(should be int)
                                                             emoji: provide a emoji 
                                                             role_id: provide the ID of the role u want the users to get.
                                                               
```
  
 Example image:
![2D6847BB-E493-4D06-AFC2-1F694D96F19E](https://user-images.githubusercontent.com/75667833/135415114-36f0aa83-00b2-4ba3-9ede-b6dcd319d0e0.jpeg)
